services:
  job-agent:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: job-agent:latest
    container_name: job-agent-app
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - job_agent_net
    dns:
      - 114.114.114.114
      - 8.8.8.8

networks:
  job_agent_net:
    driver: bridge
    name: job_agent_net