services:
  job-agent:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: job-agent:latest
    container_name: job-agent-app
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    network_mode: "bridge"